### ISSUE TITLE
关于人机验证界面的问题

### ISSUE THREAD

**Issue by 2722183335** [xuanxuan-0403/hanime-spider#1]
绅士们,你们好.
我遇到了以下问题:
我的浏览器可以直接访问到,但是我调用main.py时出现了无法连接.
后续通过ApiFox测试发现,直接调用会触发Cloudflare人机验证界面.
请问有什么办法解决吗?

**Comment by xuanxuan-0403** [comment]
当前触发人机验证并没有免费的解决方案，想要实现纯自动化需要使用付费的打码器跳过人机验证，当前解决方案只能事先打开网站把人机验证过了

**Comment by 2722183335** [comment]
你好,绅士,我找到了一个仓库,并且使用它完成了跳过Cloudflare的验证.
https://github.com/sarperavci/CloudflareBypassForScraping.

**Comment by xuanxuan-0403** [comment]
牛逼，你更新一下仓库提个pr吧，我给你提到主分支去

**Comment by Logan147** [comment]
现在运行就报错
None
Traceback (most recent call last):
  File "test.py", line 95, in <module>
  File "test.py", line 39, in getFirstPageData
TypeError: 'NoneType' object is not iterable
[5432] Failed to execute script 'test' due to unhandled exception!

**Comment by Logan147** [comment]
在win11虚拟机里运行的hanime-spider.exe，发现用不了了
